openapi: 3.0.3
info:
  title: 'Test test test'
  description: ''
  version: 1.0.0
servers:
  -
    url: ''
paths:
  /api/v1/products:
    get:
      summary: ''
      description: ''
      parameters:
        -
          in: query
          name: page
          description: Page.
          example: 1
          required: true
          schema:
            type: integer
            description: Page.
            example: 1
        -
          in: query
          name: limit
          description: Limit.
          example: 5
          required: false
          schema:
            type: integer
            description: Limit.
            example: 5
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  current_page: 1
                  data:
                    -
                      id: 0
                      name: 'H&M t-shirt blue'
                      description: null
                      price: 500
                      published_at: '2022-12-06 17:39:21'
                      created_at: '2022-12-06T17:39:21.000000Z'
                      updated_at: '2022-12-06T17:39:21.000000Z'
                    -
                      id: 9223372036854775807
                      name: 'Springfild jeans white'
                      description: null
                      price: 400
                      published_at: '2022-12-06 17:39:21'
                      created_at: '2022-12-06T17:39:21.000000Z'
                      updated_at: '2022-12-06T17:39:21.000000Z'
                    -
                      id: 47
                      name: 'Modis coat red'
                      description: null
                      price: 900
                      published_at: '2022-12-06 17:39:21'
                      created_at: '2022-12-06T17:39:21.000000Z'
                      updated_at: '2022-12-06T17:39:21.000000Z'
                    -
                      id: 9223372036854775807
                      name: 'Springfild dress  black'
                      description: null
                      price: 400
                      published_at: '2022-12-06 17:39:20'
                      created_at: '2022-12-06T17:39:20.000000Z'
                      updated_at: '2022-12-06T17:39:20.000000Z'
                    -
                      id: 0
                      name: 'Springfild skirt red'
                      description: null
                      price: 700
                      published_at: '2022-12-06 17:39:21'
                      created_at: '2022-12-06T17:39:21.000000Z'
                      updated_at: '2022-12-06T17:39:21.000000Z'
                  first_page_url: 'http://localhost/api/v1/products?page=1'
                  from: 1
                  last_page: 20
                  last_page_url: 'http://localhost/api/v1/products?page=20'
                  links:
                    -
                      url: null
                      label: pagination.previous
                      active: false
                    -
                      url: 'http://localhost/api/v1/products?page=1'
                      label: '1'
                      active: true
                    -
                      url: 'http://localhost/api/v1/products?page=2'
                      label: '2'
                      active: false
                    -
                      url: 'http://localhost/api/v1/products?page=3'
                      label: '3'
                      active: false
                    -
                      url: 'http://localhost/api/v1/products?page=4'
                      label: '4'
                      active: false
                    -
                      url: 'http://localhost/api/v1/products?page=5'
                      label: '5'
                      active: false
                    -
                      url: 'http://localhost/api/v1/products?page=6'
                      label: '6'
                      active: false
                    -
                      url: 'http://localhost/api/v1/products?page=7'
                      label: '7'
                      active: false
                    -
                      url: 'http://localhost/api/v1/products?page=8'
                      label: '8'
                      active: false
                    -
                      url: 'http://localhost/api/v1/products?page=9'
                      label: '9'
                      active: false
                    -
                      url: 'http://localhost/api/v1/products?page=10'
                      label: '10'
                      active: false
                    -
                      url: null
                      label: ...
                      active: false
                    -
                      url: 'http://localhost/api/v1/products?page=19'
                      label: '19'
                      active: false
                    -
                      url: 'http://localhost/api/v1/products?page=20'
                      label: '20'
                      active: false
                    -
                      url: 'http://localhost/api/v1/products?page=2'
                      label: pagination.next
                      active: false
                  next_page_url: 'http://localhost/api/v1/products?page=2'
                  path: 'http://localhost/api/v1/products'
                  per_page: 5
                  prev_page_url: null
                  to: 5
                  total: 100
                properties:
                  current_page:
                    type: integer
                    example: 1
                  data:
                    type: array
                    example:
                      -
                        id: 0
                        name: 'H&M t-shirt blue'
                        description: null
                        price: 500
                        published_at: '2022-12-06 17:39:21'
                        created_at: '2022-12-06T17:39:21.000000Z'
                        updated_at: '2022-12-06T17:39:21.000000Z'
                      -
                        id: 9223372036854775807
                        name: 'Springfild jeans white'
                        description: null
                        price: 400
                        published_at: '2022-12-06 17:39:21'
                        created_at: '2022-12-06T17:39:21.000000Z'
                        updated_at: '2022-12-06T17:39:21.000000Z'
                      -
                        id: 47
                        name: 'Modis coat red'
                        description: null
                        price: 900
                        published_at: '2022-12-06 17:39:21'
                        created_at: '2022-12-06T17:39:21.000000Z'
                        updated_at: '2022-12-06T17:39:21.000000Z'
                      -
                        id: 9223372036854775807
                        name: 'Springfild dress  black'
                        description: null
                        price: 400
                        published_at: '2022-12-06 17:39:20'
                        created_at: '2022-12-06T17:39:20.000000Z'
                        updated_at: '2022-12-06T17:39:20.000000Z'
                      -
                        id: 0
                        name: 'Springfild skirt red'
                        description: null
                        price: 700
                        published_at: '2022-12-06 17:39:21'
                        created_at: '2022-12-06T17:39:21.000000Z'
                        updated_at: '2022-12-06T17:39:21.000000Z'
                    items:
                      type: object
                  first_page_url:
                    type: string
                    example: 'http://localhost/api/v1/products?page=1'
                  from:
                    type: integer
                    example: 1
                  last_page:
                    type: integer
                    example: 20
                  last_page_url:
                    type: string
                    example: 'http://localhost/api/v1/products?page=20'
                  links:
                    type: array
                    example:
                      -
                        url: null
                        label: pagination.previous
                        active: false
                      -
                        url: 'http://localhost/api/v1/products?page=1'
                        label: '1'
                        active: true
                      -
                        url: 'http://localhost/api/v1/products?page=2'
                        label: '2'
                        active: false
                      -
                        url: 'http://localhost/api/v1/products?page=3'
                        label: '3'
                        active: false
                      -
                        url: 'http://localhost/api/v1/products?page=4'
                        label: '4'
                        active: false
                      -
                        url: 'http://localhost/api/v1/products?page=5'
                        label: '5'
                        active: false
                      -
                        url: 'http://localhost/api/v1/products?page=6'
                        label: '6'
                        active: false
                      -
                        url: 'http://localhost/api/v1/products?page=7'
                        label: '7'
                        active: false
                      -
                        url: 'http://localhost/api/v1/products?page=8'
                        label: '8'
                        active: false
                      -
                        url: 'http://localhost/api/v1/products?page=9'
                        label: '9'
                        active: false
                      -
                        url: 'http://localhost/api/v1/products?page=10'
                        label: '10'
                        active: false
                      -
                        url: null
                        label: ...
                        active: false
                      -
                        url: 'http://localhost/api/v1/products?page=19'
                        label: '19'
                        active: false
                      -
                        url: 'http://localhost/api/v1/products?page=20'
                        label: '20'
                        active: false
                      -
                        url: 'http://localhost/api/v1/products?page=2'
                        label: pagination.next
                        active: false
                    items:
                      type: object
                  next_page_url:
                    type: string
                    example: 'http://localhost/api/v1/products?page=2'
                  path:
                    type: string
                    example: 'http://localhost/api/v1/products'
                  per_page:
                    type: integer
                    example: 5
                  prev_page_url:
                    type: string
                    example: null
                  to:
                    type: integer
                    example: 5
                  total:
                    type: integer
                    example: 100
      tags:
        - Endpoints
      security: []
  /api/v1/order/create:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                  description: 'User id.'
                  example: 384b0e3a-ce7f-4caf-8512-97cf1dcd0a11
                products:
                  type: array
                  description: Products.
                  example:
                    - est
                  items:
                    type: string
      security: []
tags:
  -
    name: Endpoints
    description: ''
